local TCFrame = game.Workspace:WaitForChild("TableCFrame")

local cardboard = TCFrame:WaitForChild("cardboard")
local BigPresent = TCFrame:WaitForChild("BigPresent")
local Bread = TCFrame:WaitForChild("Bread")
local HotChocaTwo = TCFrame:WaitForChild("HotChocaTwo")
local HotChocaOne = TCFrame:WaitForChild("HotChocaOne")
local BigerPresent = TCFrame:WaitForChild("BigerPresent")
local PresentBigRed = TCFrame:WaitForChild("PresentBigRed")
local PresentBigMesg = TCFrame:WaitForChild("PresentBigMesg")
local PresentBigYell = TCFrame:WaitForChild("PresentBigYell")
local PresentBigYellTwo = TCFrame:WaitForChild("PresentBigYellTwo")
local MBurger = TCFrame:WaitForChild("MBurger")

local player = game:GetService("Players").LocalPlayer
local Character =  player.CharacterAdded or player.Character.Wait()

local Cooldown = task.wait(10)
function Touched()
	if Character then
	cardboard.Touched:Connect(function()
		task.wait(Cooldown)
		cardboard.Orientation = Vector3.new(-6.207, -87.68, 0)
		cardboard.Position = Vector3.new(129.976, 11.565, -88.284)
	end)
	MBurger.Touched:Connect(function()
		task.wait(Cooldown)
		MBurger.Orientation = Vector3.new(0, -134, 0)
		MBurger.Position = Vector3.new(144.755, 7.089, 258.035)
	end)
	BigerPresent.Touched:Connect(function()
		task.wait(Cooldown)
		BigerPresent.Orientation = Vector3.new(0, -26.292, 0)
		BigerPresent.Position = Vector3.new(141.502, 6.7, -96.533)
	end)
	BigPresent.Touched:Connect(function()
		task.wait(Cooldown)
		BigPresent.Orientation = Vector3.new(0, 27.421, 0)
		BigPresent.Position = Vector3.new(106.407, 4.547, -99.777)
	end)
	HotChocaTwo.Touched:Connect(function()
		task.wait(Cooldown)
		HotChocaTwo.Orientation = Vector3.new(0, -44, 0)
		HotChocaTwo.Position = Vector3.new(117.515, 6.428, -93.66)
	end)
	PresentBigRed.Touched:Connect(function()
		task.wait(Cooldown)
		PresentBigRed.Orientation = Vector3.new(0, -109.834, 0)
		PresentBigRed.Position = Vector3.new(103.753, 3.792, -97.664)
	end)
	Bread.Touched:Connect(function()
		task.wait(Cooldown)
		Bread.Orientation = Vector3.new(0, 171.666, 0)
		Bread.Position = Vector3.new(122.906, 7.581, -98.266)
	end)
	PresentBigRed.Touched:Connect(function()
		task.wait(Cooldown)
		PresentBigRed.Orientation = Vector3.new(0, 171.666, 0)
		PresentBigRed.Position = Vector3.new(122.906, 7.581, -98.266)
	end)
	HotChocaOne.Touched:Connect(function()
		task.wait(Cooldown)
		HotChocaOne.Orientation = Vector3.new(0, -144.309, 0)
		HotChocaOne.Position = Vector3.new(122.235, 6.428, -90.006)
	end)
	PresentBigYellTwo.Touched:Connect(function()
		task.wait(Cooldown)
		PresentBigYellTwo.Orientation = Vector3.new(0, 91.871, 0)
		PresentBigYellTwo.Position = Vector3.new(100.607, 6.834, -94.893)
	end)
	PresentBigYell.Touched:Connect(function()
		task.wait(Cooldown)
		PresentBigYell.Orientation = Vector3.new(0, 107.61, 0)
		PresentBigYell.Position = Vector3.new(120.01, 6.834, -113.45)
	end)
	PresentBigMesg.Touched:Connect(function()
		task.wait(Cooldown)
		PresentBigMesg.Orientation = Vector3.new(0, 0.43, 0)
		PresentBigMesg.Position = Vector3.new(131.748, 4.088, -81.438)
	end)
	end
end

Touched()