Имя: Codetime Stats
на:
  расписание:
    -крон: "0 21 * * *" 
  workflow_dispatch: # Для ручного запуска
Вакансии:
  Обновление-чтение:
    забегает: Ubuntu-Latest
    шаги:
      - Использование: Действия/Оформление@v3
      - Имя: Получите статистику Codetime
        БЕГАТЬ: |
          PIP установить запросы
          Python Generate_codetime_stats.py
      - Имя: Зафиксировать изменения
        Использование: Stefanzweifel/Git-Auto-Commit-Action@V.4
        С:
          Commit_message: "Обновление статистики Codetime"
