name: CodeTime Stats
on:
  schedule:
    - cron: "0 21 * * *" # Запуск в 00:00 MSK (21:00 UTC)
  workflow_dispatch: # Ручной запуск

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}

      - name: Fetch CodeTime Data
        run: |
          pip install requests
          python codetime_stats.py

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "📊 Update CodeTime stats"
          token: ${{ secrets.GH_TOKEN }}
