name: Waka Readme
on:
  schedule:
    - cron: "0 0 * * *" # Каждый день в полночь UTC
  workflow_dispatch: # Запуск вручную

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Добавляем разрешение на запись
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}  # Используем встроенный токен
          persist-credentials: true  # Сохраняем учетные данные
      - name: Update WakaTime Stats
        uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Используем тот же токен
          USERNAME: vvladislovv
          SHOW_COMMIT: "False"
          SHOW_TOTAL_CODE_TIME: "False"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_SHORT_INFO: "False"
          SHOW_OS: "False"
          SHOW_TIMEZONE: "False"
          SHOW_TIME: "False"
          SHOW_EDITORS: "False"
          HIDE_TIMELINE: "True"
          DEBUG_LOGGING: "False"
