name: Waka Readme
on:
  schedule:
    - cron: "0 0 * * *"  # Обновлять каждый день в 00:00 UTC
  workflow_dispatch:

permissions:  # <- Добавьте этот блок здесь (на уровне корня workflow)
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_COMMIT: "false"
          SHOW_PROFILE_VIEWS: "false"
          SHOW_OS: "false"
          SHOW_TIMEZONE: "false"
          DEBUG_LOGGING: "false"
