name: Waka Readme
on:
  schedule:
    - cron: "0 0 * * *" # Каждый день в полночь UTC
  workflow_dispatch: # Запуск вручную

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}
      - name: Update WakaTime Stats
        uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          USERNAME: vvladislovv # Ваш никнейм GitHub
