name: Waka Readme
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true
      
      - name: Update WakaTime Stats
        uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SHOW_COMMIT: "false"
          SHOW_TOTAL_CODE_TIME: "false"
          SHOW_PROFILE_VIEWS: "false"
          SHOW_SHORT_INFO: "false"
          SHOW_OS: "false"
          SHOW_TIMEZONE: "false"
          SHOW_EDITORS: "false"
          DEBUG_LOGGING: "false"
